POST http://localhost:5190/breakfasts
Content-Type: application/json

{
  "name": "Vd",
  "description": "V..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}

###

GET http://localhost:5190/Breakfasts/1f5a2f14-c383-4bfe-ab8e-842f138d3f6c