
@id=1f5a2f14-c383-4bfe-ab8e-842f138d3f6c
PUT http://localhost:5190/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "TESTESTTEST",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}